install.packages("ggplot2")
install.packages("dplyr")
install.packages("climdex.pcic")
install.packages("MCMCglmm")
install.packages("devtools")
install.packages("xtable")
install.packages("betapart")
install.packages("gdata")
install.packages("doSNOW")
install.packages("foreach")
install.packages("MCMCpack")

require(devtools)
install_version("evaluate", version = "0.13", repos = "http://cran.us.r-project.org", upgrade = "never")
install_version("knitr", version = "1.22", repos = "http://cran.us.r-project.org", upgrade = "never")
install_version("rmarkdown", version = "2.10", repos = "http://cran.us.r-project.org", upgrade = "never")
install_version("xfun", version = "0.21", repos = "http://cran.us.r-project.org", upgrade = "never")
